name: match_game
description: A new Flutter project.

version: 1.0.0

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  provider: ^3.1.0
  shared_preferences: ^0.5.3+4
  dynamic_theme: ^1.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:

  uses-material-design: true


  fonts:
    - family: Rubik
      fonts:
        - asset: assets/Rubik-Regular.ttf

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
